# Generated by Django 5.1.3 on 2025-04-03 07:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de Font Awesome para el icono', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Productos(bagueteria)',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('pais_origen', models.CharField(max_length=50)),
                ('año_fundacion', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_estimada_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'En planificación'), ('CONSTRUCCION', 'En construcción'), ('FINALIZADO', 'Finalizado'), ('ENTREGADO', 'Entregado')], default='PLANIFICACION', max_length=15)),
                ('imagen_principal', models.ImageField(upload_to='construccion/')),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('CLIENTE', 'Cliente'), ('EMPLEADO', 'Empleado'), ('ADMIN', 'Administrador')], default='CLIENTE', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARACION', 'En preparación'), ('LISTO', 'Listo para recoger'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pedido(bagueteria)',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo_pan', models.CharField(blank=True, choices=[('TRADICIONAL', 'Tradicional'), ('INTEGRAL', 'Integral'), ('SIN_GLUTEN', 'Sin Gluten')], max_length=15, null=True)),
                ('imagen', models.ImageField(upload_to='bagueteria/')),
                ('disponible', models.BooleanField(default=True)),
                ('ingredientes', models.TextField(blank=True)),
                ('tiempo_preparacion', models.IntegerField(blank=True, help_text='Tiempo en minutos', null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_centroonline_ventura.categoriaproducto')),
            ],
            options={
                'verbose_name_plural': 'Producto(bagueteria)',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_centroonline_ventura.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_centroonline_ventura.producto')),
            ],
            options={
                'verbose_name_plural': 'Detalle de pedido (bagueteria)',
            },
        ),
        migrations.CreateModel(
            name='ProductoMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ALIMENTOS', 'Alimentos'), ('BEBIDAS', 'Bebidas'), ('LIMPIEZA', 'Limpieza'), ('OTROS', 'Otros')], max_length=10)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='market/')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_centroonline_ventura.proveedor')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='construccion/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app_centroonline_ventura.proyectoconstruccion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('tipo', models.CharField(choices=[('SEDAN', 'Sedán'), ('SUV', 'SUV'), ('PICKUP', 'Pickup'), ('DEPORTIVO', 'Deportivo'), ('ELECTRICO', 'Eléctrico'), ('HIBRIDO', 'Híbrido')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kilometraje', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('transmision', models.CharField(choices=[('AUTOMATICO', 'Automático'), ('MANUAL', 'Manual'), ('CVT', 'CVT')], max_length=10)),
                ('motor', models.CharField(max_length=50)),
                ('potencia', models.IntegerField(help_text='Caballos de fuerza')),
                ('descripcion', models.TextField()),
                ('imagen_principal', models.ImageField(upload_to='vehiculos/')),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('destacado', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_centroonline_ventura.marca')),
            ],
            options={
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_test', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_centroonline_ventura.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/galeria/')),
                ('orden', models.IntegerField(default=0)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app_centroonline_ventura.vehiculo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
