# Generated by Django 5.1.3 on 2025-04-09 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_centroonline_ventura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfumeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('U', 'Unisex')], max_length=1)),
                ('imagen', models.ImageField(upload_to='perfumerias/')),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No Ficción'), ('educativo', 'Educativo'), ('ciencia', 'Ciencia'), ('historia', 'Historia'), ('fantasia', 'Fantasía'), ('romance', 'Romance'), ('arte', 'Arte'), ('misterio', 'Misterio'), ('infantil', 'Infantil')], max_length=100)),
                ('imagen', models.ImageField(upload_to='productos_estudio/')),
            ],
            options={
                'verbose_name_plural': 'Libreria',
            },
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='reservado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_centroonline_ventura.vehiculo')),
            ],
            options={
                'verbose_name': 'Reserva de vehículo',
                'verbose_name_plural': 'Reservas de vehículos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_centroonline_ventura.categoria')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='app_centroonline_ventura.pais')),
            ],
        ),
    ]
