# Generated by Django 5.1.3 on 2025-04-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_centroonline_ventura', '0002_vehiculo_fecha_reserva_vehiculo_reservado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfumeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('imagen', models.ImageField(upload_to='perfumerias/')),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
