# Generated by Django 5.1.3 on 2025-04-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_centroonline_ventura', '0002_perfumeria_productoestudio_viaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaProducto',
        ),
    ]
