# Generated by Django 5.1.3 on 2025-04-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_centroonline_ventura', '0002_vehiculo_disponible_vehiculo_reservado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
