# Generated by Django 5.1.3 on 2025-04-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_centroonline_ventura', '0003_perfumeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumeria',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('U', 'Unisex')], max_length=1),
        ),
    ]
