# Generated by Django 5.1.3 on 2025-04-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_centroonline_ventura', '0004_alter_perfumeria_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No Ficción'), ('educativo', 'Educativo'), ('ciencia', 'Ciencia'), ('historia', 'Historia'), ('fantasia', 'Fantasía'), ('romance', 'Romance'), ('arte', 'Arte'), ('misterio', 'Misterio'), ('infantil', 'Infantil')], max_length=100)),
                ('imagen', models.ImageField(upload_to='productos_estudio/')),
            ],
        ),
    ]
