# Generated by Django 5.1.3 on 2025-04-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_centroonline_ventura', '0005_productoestudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='destinos/')),
                ('precio_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('Playa', 'Playa'), ('Montaña', 'Montaña'), ('Ciudad', 'Ciudad')], max_length=50)),
                ('imagen', models.ImageField(upload_to='guias/')),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='productoestudio',
            options={'verbose_name_plural': 'Libreria'},
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock', models.IntegerField()),
                ('imagen_principal', models.ImageField(upload_to='productos/')),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('nuevo', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_centroonline_ventura.categoria')),
            ],
        ),
    ]
